//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinanceApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Debt
    {
        public int IDDebt { get; set; }
        public int IDUser { get; set; }
        public int IDTypeDebt { get; set; }
        public decimal AmountDebt { get; set; }
        public decimal PaidAmountDebt { get; set; }
        public string NoteDebt { get; set; }
        public System.DateTime DateDebt { get; set; }
    
        public virtual TypeDebt TypeDebt { get; set; }
        public virtual Users Users { get; set; }
        public bool IsClosed
        {
            get => PaidAmountDebt >= AmountDebt;
        }
    }
}
