//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinanceApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Goal
    {
        public int IDGoal { get; set; }
        public string NameGoal { get; set; }
        public decimal PaidAmountGoal { get; set; }
        public decimal AmountGoal { get; set; }
        public int IDUser { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
