//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinanceApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public int IDTransaction { get; set; }
        public int IDUser { get; set; }
        public System.DateTime DateTransaction { get; set; }
        public int IDCategory { get; set; }
        public decimal AmountTransaction { get; set; }
        public string NoteTransaction { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Users Users { get; set; }
    }
}
